import type {
  NewsArticle,
  AITool,
  Guide,
  Prompt,
  AIModel,
  ResearchPaper,
  AIEvent,
  AIJob,
  Company,
} from "./types";

export const mockNews: NewsArticle[] = [
  {
    id: "1",
    slug: "openai-gpt-5-launch",
    title: "OpenAI Launches GPT-5 with Unprecedented Reasoning Capabilities",
    summary:
      "OpenAI has released GPT-5, their most advanced language model yet, featuring breakthrough reasoning, multimodal understanding, and a 1M token context window.",
    content: "",
    source: "OpenAI Blog",
    sourceUrl: "https://openai.com/blog",
    imageUrl: "/placeholder-news.jpg",
    category: "Model Release",
    tags: ["OpenAI", "GPT-5", "LLM", "AI Models"],
    impactScore: 98,
    publishedAt: "2026-07-11T08:00:00Z",
    createdAt: "2026-07-11T08:00:00Z",
    relatedTools: ["chatgpt"],
  },
  {
    id: "2",
    slug: "anthropic-claude-opus-5-release",
    title: "Anthropic Releases Claude Opus 5 — Sets New Benchmarks Across the Board",
    summary:
      "Claude Opus 5 achieves state-of-the-art performance on coding, math, and reasoning benchmarks while maintaining industry-leading safety standards.",
    content: "",
    source: "Anthropic",
    sourceUrl: "https://anthropic.com",
    imageUrl: "/placeholder-news.jpg",
    category: "Model Release",
    tags: ["Anthropic", "Claude", "LLM", "Benchmarks"],
    impactScore: 96,
    publishedAt: "2026-07-10T14:00:00Z",
    createdAt: "2026-07-10T14:00:00Z",
    relatedTools: ["claude"],
  },
  {
    id: "3",
    slug: "google-gemini-ultra-2-multimodal",
    title: "Google DeepMind Unveils Gemini Ultra 2 with Native Video Understanding",
    summary:
      "Gemini Ultra 2 can process and reason over hours of video content natively, opening new possibilities for media analysis and content creation.",
    content: "",
    source: "Google DeepMind",
    sourceUrl: "https://deepmind.google",
    imageUrl: "/placeholder-news.jpg",
    category: "Model Release",
    tags: ["Google", "Gemini", "Multimodal", "Video AI"],
    impactScore: 94,
    publishedAt: "2026-07-10T10:00:00Z",
    createdAt: "2026-07-10T10:00:00Z",
    relatedTools: ["gemini"],
  },
  {
    id: "4",
    slug: "runway-gen-4-real-time-video",
    title: "Runway Launches Gen-4: Real-Time AI Video Generation at 4K",
    summary:
      "Runway's Gen-4 model can generate photorealistic 4K video in real-time, with precise control over camera movements, lighting, and character consistency.",
    content: "",
    source: "Runway",
    sourceUrl: "https://runway.ml",
    imageUrl: "/placeholder-news.jpg",
    category: "Product Launch",
    tags: ["Runway", "Video Generation", "Gen-4", "Creative AI"],
    impactScore: 91,
    publishedAt: "2026-07-09T16:00:00Z",
    createdAt: "2026-07-09T16:00:00Z",
    relatedTools: ["runway"],
  },
  {
    id: "5",
    slug: "meta-llama-4-open-source",
    title: "Meta Releases Llama 4 — Most Capable Open-Source Model Ever",
    summary:
      "Llama 4 matches proprietary models on key benchmarks while remaining fully open-source, with weights available for commercial use.",
    content: "",
    source: "Meta AI",
    sourceUrl: "https://ai.meta.com",
    imageUrl: "/placeholder-news.jpg",
    category: "Open Source",
    tags: ["Meta", "Llama", "Open Source", "LLM"],
    impactScore: 93,
    publishedAt: "2026-07-09T12:00:00Z",
    createdAt: "2026-07-09T12:00:00Z",
    relatedTools: ["llama"],
  },
  {
    id: "6",
    slug: "midjourney-v7-3d-generation",
    title: "Midjourney V7 Adds Full 3D Scene Generation from Text Prompts",
    summary:
      "Midjourney's latest version can generate complete 3D scenes, characters, and environments directly from text descriptions.",
    content: "",
    source: "Midjourney",
    sourceUrl: "https://midjourney.com",
    imageUrl: "/placeholder-news.jpg",
    category: "Product Update",
    tags: ["Midjourney", "3D", "Image Generation"],
    impactScore: 88,
    publishedAt: "2026-07-08T18:00:00Z",
    createdAt: "2026-07-08T18:00:00Z",
    relatedTools: ["midjourney"],
  },
  {
    id: "7",
    slug: "deepseek-v4-coding-dominance",
    title: "DeepSeek V4 Achieves Highest Ever Score on SWE-Bench",
    summary:
      "DeepSeek's latest model resolves 78% of real-world GitHub issues autonomously, setting a new record for AI coding capabilities.",
    content: "",
    source: "DeepSeek",
    sourceUrl: "https://deepseek.com",
    imageUrl: "/placeholder-news.jpg",
    category: "Benchmark",
    tags: ["DeepSeek", "Coding", "SWE-Bench"],
    impactScore: 89,
    publishedAt: "2026-07-08T09:00:00Z",
    createdAt: "2026-07-08T09:00:00Z",
    relatedTools: ["deepseek"],
  },
  {
    id: "8",
    slug: "elevenlabs-universal-voice-cloning",
    title: "ElevenLabs Launches Instant Voice Cloning in 30+ Languages",
    summary:
      "New universal voice cloning technology needs only 10 seconds of audio to create a natural-sounding voice clone that works across 30 languages.",
    content: "",
    source: "ElevenLabs",
    sourceUrl: "https://elevenlabs.io",
    imageUrl: "/placeholder-news.jpg",
    category: "Product Launch",
    tags: ["ElevenLabs", "Voice AI", "TTS", "Audio"],
    impactScore: 85,
    publishedAt: "2026-07-07T14:00:00Z",
    createdAt: "2026-07-07T14:00:00Z",
    relatedTools: ["elevenlabs"],
  },
];

export const mockTools: AITool[] = [
  {
    id: "1",
    slug: "chatgpt",
    name: "ChatGPT",
    tagline: "Advanced AI assistant for conversation, coding, analysis, and creation",
    description:
      "ChatGPT is OpenAI's conversational AI platform powered by GPT-5. It offers advanced reasoning, code generation, image creation with DALL-E, web browsing, and plugin support.",
    logoUrl: "/logos/openai.svg",
    screenshotUrl: "/screenshots/chatgpt.jpg",
    websiteUrl: "https://chat.openai.com",
    category: "chatbots",
    subcategory: "General Assistant",
    pricing: {
      model: "freemium",
      startingPrice: "$20/mo",
      plans: [
        { name: "Free", price: "Free", features: ["GPT-4o mini", "Limited messages", "Basic features"] },
        { name: "Plus", price: "$20/mo", features: ["GPT-5", "Unlimited messages", "DALL-E", "Advanced analysis"] },
        { name: "Pro", price: "$200/mo", features: ["Unlimited GPT-5", "o3 pro", "Extended thinking", "Priority"] },
      ],
    },
    features: ["Conversational AI", "Code generation", "Image creation", "Web browsing", "File analysis", "Voice mode"],
    tags: ["AI Chat", "GPT-5", "OpenAI", "Productivity"],
    company: "OpenAI",
    founder: "Sam Altman",
    launchDate: "2022-11-30",
    rating: 4.7,
    reviewCount: 125000,
    isFeatured: true,
    isTrending: true,
    pros: ["Most versatile AI assistant", "Excellent at coding", "Great plugin ecosystem", "Voice and vision support"],
    cons: ["Can hallucinate", "Expensive Pro tier", "Rate limits on free plan"],
    alternatives: ["claude", "gemini", "perplexity"],
    apiAvailable: true,
    changelog: [{ date: "2026-07-01", version: "GPT-5", changes: ["1M context window", "Native reasoning", "Improved coding"] }],
    createdAt: "2022-11-30",
    updatedAt: "2026-07-11",
  },
  {
    id: "2",
    slug: "claude",
    name: "Claude",
    tagline: "AI assistant focused on safety, helpfulness, and honest reasoning",
    description:
      "Claude by Anthropic is known for its careful reasoning, long-context capabilities, and strong performance on coding and analysis tasks. Opus 5 is the latest flagship.",
    logoUrl: "/logos/anthropic.svg",
    screenshotUrl: "/screenshots/claude.jpg",
    websiteUrl: "https://claude.ai",
    category: "chatbots",
    subcategory: "General Assistant",
    pricing: {
      model: "freemium",
      startingPrice: "$20/mo",
      plans: [
        { name: "Free", price: "Free", features: ["Claude Sonnet", "Limited messages"] },
        { name: "Pro", price: "$20/mo", features: ["Claude Opus", "More messages", "Projects", "Priority"] },
        { name: "Max", price: "$100/mo", features: ["Unlimited Opus", "Extended thinking", "Claude Code"] },
      ],
    },
    features: ["Long context (200K)", "Code analysis", "Document understanding", "Artifacts", "Projects", "Claude Code"],
    tags: ["AI Chat", "Claude", "Anthropic", "Coding"],
    company: "Anthropic",
    founder: "Dario Amodei",
    launchDate: "2023-03-14",
    rating: 4.8,
    reviewCount: 89000,
    isFeatured: true,
    isTrending: true,
    pros: ["Best at careful reasoning", "200K context window", "Strong at coding", "Artifacts for creation"],
    cons: ["Can be overly cautious", "Smaller plugin ecosystem"],
    alternatives: ["chatgpt", "gemini", "deepseek"],
    apiAvailable: true,
    changelog: [{ date: "2026-07-10", version: "Opus 5", changes: ["State-of-the-art reasoning", "Improved coding", "Better tool use"] }],
    createdAt: "2023-03-14",
    updatedAt: "2026-07-11",
  },
  {
    id: "3",
    slug: "midjourney",
    name: "Midjourney",
    tagline: "AI-powered image generation with unmatched artistic quality",
    description:
      "Midjourney creates stunning images from text descriptions. V7 introduces 3D scene generation, character consistency, and photorealistic rendering.",
    logoUrl: "/logos/midjourney.svg",
    screenshotUrl: "/screenshots/midjourney.jpg",
    websiteUrl: "https://midjourney.com",
    category: "image-generation",
    subcategory: "Art & Design",
    pricing: {
      model: "paid",
      startingPrice: "$10/mo",
      plans: [
        { name: "Basic", price: "$10/mo", features: ["200 generations/mo", "Standard quality"] },
        { name: "Standard", price: "$30/mo", features: ["Unlimited relaxed", "15h fast"] },
        { name: "Pro", price: "$60/mo", features: ["Unlimited relaxed", "30h fast", "Stealth mode"] },
      ],
    },
    features: ["Text to image", "Image editing", "3D scenes", "Style transfer", "Upscaling", "Character consistency"],
    tags: ["Image Generation", "Art", "Design", "Creative"],
    company: "Midjourney",
    founder: "David Holz",
    launchDate: "2022-07-12",
    rating: 4.9,
    reviewCount: 200000,
    isFeatured: true,
    isTrending: true,
    pros: ["Best artistic quality", "Active community", "Constant improvements", "3D generation"],
    cons: ["No free tier", "Discord-based (moving to web)", "Learning curve for prompts"],
    alternatives: ["dall-e", "stable-diffusion", "ideogram"],
    apiAvailable: false,
    changelog: [{ date: "2026-07-08", version: "V7", changes: ["3D scene generation", "Character consistency", "4K output"] }],
    createdAt: "2022-07-12",
    updatedAt: "2026-07-08",
  },
  {
    id: "4",
    slug: "runway",
    name: "Runway",
    tagline: "AI-powered creative tools for video generation and editing",
    description:
      "Runway is a creative AI platform specializing in video generation and editing. Gen-4 enables real-time 4K video creation with precise controls.",
    logoUrl: "/logos/runway.svg",
    screenshotUrl: "/screenshots/runway.jpg",
    websiteUrl: "https://runway.ml",
    category: "video-generation",
    subcategory: "Video Production",
    pricing: {
      model: "freemium",
      startingPrice: "$15/mo",
      plans: [
        { name: "Free", price: "Free", features: ["125 credits", "720p export", "3 projects"] },
        { name: "Standard", price: "$15/mo", features: ["625 credits/mo", "4K export", "Unlimited projects"] },
        { name: "Pro", price: "$35/mo", features: ["2250 credits/mo", "4K export", "Custom models"] },
      ],
    },
    features: ["Text to video", "Image to video", "Video editing", "Motion brush", "Camera control", "Green screen"],
    tags: ["Video Generation", "Creative AI", "Editing"],
    company: "Runway",
    founder: "Cristóbal Valenzuela",
    launchDate: "2018-01-01",
    rating: 4.6,
    reviewCount: 45000,
    isFeatured: true,
    isTrending: true,
    pros: ["Best video generation quality", "Intuitive interface", "Fast iteration", "Professional tools"],
    cons: ["Credits run out quickly", "Expensive for heavy use", "Watermarks on free plan"],
    alternatives: ["pika", "kling", "sora"],
    apiAvailable: true,
    changelog: [{ date: "2026-07-09", version: "Gen-4", changes: ["Real-time generation", "4K output", "Camera controls"] }],
    createdAt: "2018-01-01",
    updatedAt: "2026-07-09",
  },
  {
    id: "5",
    slug: "cursor",
    name: "Cursor",
    tagline: "AI-first code editor that helps you build software faster",
    description:
      "Cursor is a VS Code fork enhanced with AI capabilities. It offers intelligent code completion, chat-driven editing, and codebase-aware suggestions.",
    logoUrl: "/logos/cursor.svg",
    screenshotUrl: "/screenshots/cursor.jpg",
    websiteUrl: "https://cursor.com",
    category: "coding",
    subcategory: "IDE",
    pricing: {
      model: "freemium",
      startingPrice: "$20/mo",
      plans: [
        { name: "Free", price: "Free", features: ["2000 completions", "50 slow premium requests"] },
        { name: "Pro", price: "$20/mo", features: ["Unlimited completions", "500 fast requests", "Unlimited slow"] },
        { name: "Business", price: "$40/mo", features: ["Everything in Pro", "Team management", "SSO"] },
      ],
    },
    features: ["AI code completion", "Chat editing", "Codebase context", "Multi-file editing", "Terminal commands"],
    tags: ["Code Editor", "AI Coding", "IDE", "Developer Tools"],
    company: "Anysphere",
    founder: "Michael Truell",
    launchDate: "2023-03-01",
    rating: 4.7,
    reviewCount: 67000,
    isFeatured: true,
    isTrending: true,
    pros: ["Excellent code completion", "Fast iterations", "VS Code compatible", "Multi-model support"],
    cons: ["Subscription required for best features", "Can be resource-heavy"],
    alternatives: ["github-copilot", "windsurf", "claude-code"],
    apiAvailable: false,
    changelog: [{ date: "2026-06-15", version: "0.50", changes: ["Background agents", "Improved context", "Bug fixes"] }],
    createdAt: "2023-03-01",
    updatedAt: "2026-07-01",
  },
  {
    id: "6",
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "AI voice synthesis and cloning platform",
    description:
      "ElevenLabs offers the most natural-sounding AI voices for text-to-speech, voice cloning, dubbing, and audio content creation across 30+ languages.",
    logoUrl: "/logos/elevenlabs.svg",
    screenshotUrl: "/screenshots/elevenlabs.jpg",
    websiteUrl: "https://elevenlabs.io",
    category: "audio",
    subcategory: "Voice AI",
    pricing: {
      model: "freemium",
      startingPrice: "$5/mo",
      plans: [
        { name: "Free", price: "Free", features: ["10K characters/mo", "3 custom voices"] },
        { name: "Starter", price: "$5/mo", features: ["30K characters/mo", "10 custom voices"] },
        { name: "Creator", price: "$22/mo", features: ["100K characters/mo", "30 custom voices", "Professional voices"] },
      ],
    },
    features: ["Text to speech", "Voice cloning", "Dubbing", "Sound effects", "Voice library", "API access"],
    tags: ["Voice AI", "TTS", "Audio", "Dubbing"],
    company: "ElevenLabs",
    founder: "Piotr Dabkowski",
    launchDate: "2023-01-01",
    rating: 4.8,
    reviewCount: 52000,
    isFeatured: true,
    isTrending: false,
    pros: ["Most natural voices", "Instant voice cloning", "30+ languages", "Great API"],
    cons: ["Character limits", "Voice cloning ethics concerns"],
    alternatives: ["play-ht", "murf", "resemble-ai"],
    apiAvailable: true,
    changelog: [{ date: "2026-07-07", version: "v3", changes: ["Universal voice cloning", "30+ languages", "10s sample cloning"] }],
    createdAt: "2023-01-01",
    updatedAt: "2026-07-07",
  },
];

export const mockGuides: Guide[] = [
  {
    id: "1",
    slug: "getting-started-with-gpt5-api",
    title: "Getting Started with the GPT-5 API: A Complete Guide",
    summary: "Learn how to integrate OpenAI's GPT-5 API into your applications with practical code examples and best practices.",
    content: "",
    imageUrl: "/placeholder-guide.jpg",
    category: "coding",
    difficulty: "beginner",
    readTime: 15,
    author: "AI World Hub",
    tags: ["GPT-5", "OpenAI", "API", "Tutorial"],
    requirements: ["Python 3.10+", "OpenAI API key", "Basic Python knowledge"],
    steps: [
      { title: "Install the OpenAI SDK", content: "Install the latest OpenAI Python package.", codeExample: "pip install openai" },
      { title: "Set up authentication", content: "Configure your API key.", codeExample: 'import openai\nclient = openai.OpenAI(api_key="your-key")' },
      { title: "Make your first request", content: "Send a message and get a response.", codeExample: 'response = client.chat.completions.create(\n  model="gpt-5",\n  messages=[{"role": "user", "content": "Hello!"}]\n)' },
    ],
    relatedTools: ["chatgpt"],
    publishedAt: "2026-07-11T08:00:00Z",
  },
  {
    id: "2",
    slug: "build-ai-agent-with-claude",
    title: "Build an AI Agent with Claude: Step-by-Step Tutorial",
    summary: "Create a fully autonomous AI agent using Claude's tool use capabilities and the Anthropic SDK.",
    content: "",
    imageUrl: "/placeholder-guide.jpg",
    category: "coding",
    difficulty: "intermediate",
    readTime: 25,
    author: "AI World Hub",
    tags: ["Claude", "Anthropic", "AI Agents", "Tutorial"],
    requirements: ["Python 3.10+", "Anthropic API key", "Understanding of LLMs"],
    steps: [
      { title: "Set up the environment", content: "Install dependencies and configure credentials." },
      { title: "Define your tools", content: "Create tool definitions for your agent." },
      { title: "Build the agent loop", content: "Implement the reasoning and action loop." },
    ],
    relatedTools: ["claude"],
    publishedAt: "2026-07-10T10:00:00Z",
  },
  {
    id: "3",
    slug: "create-stunning-ai-art-midjourney",
    title: "Create Stunning AI Art with Midjourney V7",
    summary: "Master Midjourney's latest features including 3D scene generation, style mixing, and character consistency.",
    content: "",
    imageUrl: "/placeholder-guide.jpg",
    category: "image-generation",
    difficulty: "beginner",
    readTime: 12,
    author: "AI World Hub",
    tags: ["Midjourney", "AI Art", "Image Generation"],
    requirements: ["Midjourney subscription", "Discord account"],
    steps: [
      { title: "Understanding V7 prompts", content: "Learn the new prompt syntax." },
      { title: "3D scene basics", content: "Generate your first 3D scene." },
      { title: "Advanced techniques", content: "Style mixing and character consistency." },
    ],
    relatedTools: ["midjourney"],
    publishedAt: "2026-07-09T14:00:00Z",
  },
  {
    id: "4",
    slug: "ai-video-generation-complete-guide",
    title: "AI Video Generation: The Complete Guide for 2026",
    summary: "Compare Runway, Pika, Kling, and Sora — learn which tool is best for your video creation needs.",
    content: "",
    imageUrl: "/placeholder-guide.jpg",
    category: "video-generation",
    difficulty: "beginner",
    readTime: 20,
    author: "AI World Hub",
    tags: ["Video AI", "Runway", "Pika", "Kling", "Sora"],
    requirements: ["Account on any video AI platform"],
    steps: [
      { title: "Choose your platform", content: "Compare features and pricing." },
      { title: "Create your first video", content: "Generate video from text or image." },
      { title: "Edit and refine", content: "Use advanced controls for better results." },
    ],
    relatedTools: ["runway"],
    publishedAt: "2026-07-08T16:00:00Z",
  },
];

export const mockPrompts: Prompt[] = [
  {
    id: "1",
    slug: "expert-code-reviewer",
    title: "Expert Code Reviewer",
    description: "Have AI review your code like a senior engineer with detailed feedback.",
    promptText:
      "Act as a senior software engineer with 15 years of experience. Review the following code for:\n1. Bugs and potential issues\n2. Performance optimizations\n3. Security vulnerabilities\n4. Code style and best practices\n5. Suggestions for improvement\n\nProvide specific, actionable feedback with code examples for each point.\n\n```\n[PASTE YOUR CODE HERE]\n```",
    category: "coding",
    model: "GPT-5 / Claude Opus",
    tags: ["Code Review", "Programming", "Best Practices"],
    useCase: "Get expert-level code reviews instantly",
    tips: ["Include the programming language", "Provide context about what the code does", "Ask about specific concerns"],
    author: "AI World Hub",
    likes: 3420,
    saves: 1890,
    createdAt: "2026-07-01T00:00:00Z",
  },
  {
    id: "2",
    slug: "viral-content-creator",
    title: "Viral Content Creator",
    description: "Generate engaging social media content optimized for virality.",
    promptText:
      "You are a viral content strategist. Create [PLATFORM] content about [TOPIC] that:\n- Hooks in the first line\n- Uses emotional triggers\n- Includes a clear CTA\n- Is optimized for the algorithm\n- Feels authentic, not AI-generated\n\nFormat: Give me 5 variations with different angles.",
    category: "marketing",
    model: "GPT-5 / Claude",
    tags: ["Marketing", "Social Media", "Content"],
    useCase: "Create viral social media posts",
    tips: ["Specify the platform", "Include your brand voice", "Mention target audience"],
    author: "AI World Hub",
    likes: 5200,
    saves: 3100,
    createdAt: "2026-06-28T00:00:00Z",
  },
  {
    id: "3",
    slug: "midjourney-photorealistic",
    title: "Photorealistic Image Prompt",
    description: "Generate hyper-realistic images with detailed Midjourney prompts.",
    promptText:
      "[SUBJECT] in [SETTING], photographed with a Canon EOS R5, 85mm f/1.4 lens, golden hour lighting, shallow depth of field, cinematic color grading, 8K resolution, ultra detailed --ar 16:9 --v 7 --style raw --q 2",
    category: "image-generation",
    model: "Midjourney V7",
    tags: ["Midjourney", "Photography", "Photorealistic"],
    useCase: "Create photorealistic AI images",
    tips: ["Replace [SUBJECT] and [SETTING]", "Adjust aspect ratio as needed", "Try different lighting conditions"],
    author: "AI World Hub",
    likes: 8900,
    saves: 6200,
    createdAt: "2026-06-25T00:00:00Z",
  },
  {
    id: "4",
    slug: "learning-companion",
    title: "AI Learning Companion",
    description: "Transform AI into a personalized tutor that adapts to your learning style.",
    promptText:
      "You are my personal learning companion for [SUBJECT]. My current level is [BEGINNER/INTERMEDIATE/ADVANCED].\n\nTeach me using:\n- Analogies from everyday life\n- Progressive complexity\n- Quick quizzes after each concept\n- Real-world applications\n- Mnemonics and memory aids\n\nStart with the fundamentals and check my understanding before moving on. If I struggle, try a different explanation approach.",
    category: "education",
    model: "Claude / GPT-5",
    tags: ["Education", "Learning", "Tutoring"],
    useCase: "Learn any subject with a personalized AI tutor",
    tips: ["Be specific about your current level", "Tell AI about your learning preferences", "Ask for examples"],
    author: "AI World Hub",
    likes: 4100,
    saves: 2800,
    createdAt: "2026-06-20T00:00:00Z",
  },
  {
    id: "5",
    slug: "startup-pitch-generator",
    title: "Startup Pitch Generator",
    description: "Create a compelling startup pitch deck narrative in minutes.",
    promptText:
      "Create a pitch deck narrative for my startup:\n\nProduct: [YOUR PRODUCT]\nProblem: [PROBLEM YOU SOLVE]\nTarget Market: [YOUR AUDIENCE]\nBusiness Model: [HOW YOU MAKE MONEY]\n\nGenerate:\n1. Problem slide (make it emotional)\n2. Solution slide (clear value prop)\n3. Market size (TAM/SAM/SOM)\n4. Product demo talking points\n5. Business model slide\n6. Traction/milestones\n7. Team slide framework\n8. Ask slide (funding amount + use of funds)",
    category: "writing",
    model: "GPT-5 / Claude",
    tags: ["Startup", "Pitch Deck", "Business"],
    useCase: "Create investor-ready pitch narratives",
    tips: ["Include real numbers if you have them", "Be honest about stage", "Focus on the story"],
    author: "AI World Hub",
    likes: 2900,
    saves: 2100,
    createdAt: "2026-06-15T00:00:00Z",
  },
  {
    id: "6",
    slug: "ai-automation-workflow",
    title: "AI Automation Workflow Designer",
    description: "Design complex automation workflows using AI agents and tools.",
    promptText:
      "Design an automation workflow for: [YOUR TASK]\n\nRequirements:\n- Tools available: [LIST YOUR TOOLS]\n- Trigger: [WHAT STARTS THE WORKFLOW]\n- Output: [DESIRED RESULT]\n\nProvide:\n1. Step-by-step workflow diagram (in text)\n2. Tool connections and data flow\n3. Error handling for each step\n4. Estimated time savings\n5. Implementation guide",
    category: "automation",
    model: "GPT-5 / Claude",
    tags: ["Automation", "Workflow", "Productivity"],
    useCase: "Design AI-powered automation workflows",
    tips: ["List all available tools", "Define success criteria", "Consider edge cases"],
    author: "AI World Hub",
    likes: 1800,
    saves: 1200,
    createdAt: "2026-06-10T00:00:00Z",
  },
];

export const mockModels: AIModel[] = [
  { id: "1", name: "GPT-5", provider: "OpenAI", version: "5.0", category: "LLM", contextWindow: "1M", speed: 92, coding: 96, vision: true, apiPricing: "$5/1M input, $15/1M output", benchmarks: { "MMLU": 92.5, "HumanEval": 95.1, "MATH": 89.3 } },
  { id: "2", name: "Claude Opus 5", provider: "Anthropic", version: "5.0", category: "LLM", contextWindow: "200K", speed: 88, coding: 97, vision: true, apiPricing: "$15/1M input, $75/1M output", benchmarks: { "MMLU": 93.1, "HumanEval": 96.8, "MATH": 91.2 } },
  { id: "3", name: "Gemini Ultra 2", provider: "Google", version: "2.0", category: "Multimodal", contextWindow: "2M", speed: 90, coding: 93, vision: true, apiPricing: "$7/1M input, $21/1M output", benchmarks: { "MMLU": 91.8, "HumanEval": 92.4, "MATH": 88.7 } },
  { id: "4", name: "Llama 4 405B", provider: "Meta", version: "4.0", category: "Open Source", contextWindow: "256K", speed: 85, coding: 91, vision: true, apiPricing: "Free (self-host)", benchmarks: { "MMLU": 89.5, "HumanEval": 90.2, "MATH": 85.1 } },
  { id: "5", name: "Grok 3", provider: "xAI", version: "3.0", category: "LLM", contextWindow: "128K", speed: 91, coding: 90, vision: true, apiPricing: "$3/1M input, $9/1M output", benchmarks: { "MMLU": 88.9, "HumanEval": 89.5, "MATH": 84.6 } },
  { id: "6", name: "DeepSeek V4", provider: "DeepSeek", version: "4.0", category: "Coding", contextWindow: "128K", speed: 87, coding: 98, vision: false, apiPricing: "$0.5/1M input, $2/1M output", benchmarks: { "MMLU": 87.2, "HumanEval": 98.1, "MATH": 90.5 } },
];

export const mockPapers: ResearchPaper[] = [
  {
    id: "1",
    slug: "scaling-laws-beyond-transformers",
    title: "Scaling Laws Beyond Transformers: A Unified Theory of Neural Architecture Efficiency",
    authors: ["J. Chen", "A. Kumar", "S. Zhang"],
    abstract: "We present a unified framework for understanding scaling laws across different neural architectures, demonstrating that efficiency gains from architectural innovations follow predictable patterns.",
    arxivUrl: "https://arxiv.org/abs/2026.12345",
    pdfUrl: "https://arxiv.org/pdf/2026.12345",
    category: "Machine Learning",
    publishedAt: "2026-07-10T00:00:00Z",
    citations: 12,
    tags: ["Scaling Laws", "Architecture", "Efficiency"],
  },
  {
    id: "2",
    slug: "constitutional-ai-v3",
    title: "Constitutional AI v3: Self-Improving Safety Through Recursive Oversight",
    authors: ["Anthropic Research"],
    abstract: "We introduce Constitutional AI v3, which enables AI systems to recursively improve their own safety properties through multi-level constitutional hierarchies.",
    arxivUrl: "https://arxiv.org/abs/2026.12346",
    pdfUrl: "https://arxiv.org/pdf/2026.12346",
    category: "AI Safety",
    publishedAt: "2026-07-09T00:00:00Z",
    citations: 45,
    tags: ["AI Safety", "Constitutional AI", "Alignment"],
  },
  {
    id: "3",
    slug: "video-world-models",
    title: "Video World Models: Learning Physics from Unlabeled Video at Scale",
    authors: ["Google DeepMind"],
    abstract: "We train world models on 10M hours of unlabeled video, learning emergent physics simulation capabilities that transfer to robotics and video generation tasks.",
    arxivUrl: "https://arxiv.org/abs/2026.12347",
    pdfUrl: "https://arxiv.org/pdf/2026.12347",
    category: "Computer Vision",
    publishedAt: "2026-07-08T00:00:00Z",
    citations: 78,
    tags: ["World Models", "Video", "Physics", "Robotics"],
  },
];

export const mockEvents: AIEvent[] = [
  {
    id: "1",
    slug: "neurips-2026",
    title: "NeurIPS 2026",
    description: "The premier machine learning conference featuring cutting-edge research presentations, workshops, and tutorials.",
    date: "2026-12-08",
    endDate: "2026-12-14",
    location: "Vancouver, Canada",
    isVirtual: false,
    url: "https://neurips.cc",
    organizer: "NeurIPS Foundation",
    imageUrl: "/placeholder-event.jpg",
    tags: ["Conference", "Research", "ML"],
  },
  {
    id: "2",
    slug: "ai-world-summit-2026",
    title: "AI World Summit 2026",
    description: "Global summit bringing together AI leaders, researchers, and practitioners to discuss the future of artificial intelligence.",
    date: "2026-09-15",
    endDate: "2026-09-17",
    location: "San Francisco, CA",
    isVirtual: true,
    url: "https://aiworldsummit.com",
    organizer: "AI World",
    imageUrl: "/placeholder-event.jpg",
    tags: ["Summit", "Industry", "Networking"],
  },
  {
    id: "3",
    slug: "icml-2026",
    title: "ICML 2026",
    description: "International Conference on Machine Learning — one of the top venues for ML research.",
    date: "2026-07-21",
    endDate: "2026-07-27",
    location: "Vienna, Austria",
    isVirtual: false,
    url: "https://icml.cc",
    organizer: "ICML",
    imageUrl: "/placeholder-event.jpg",
    tags: ["Conference", "Research", "ML"],
  },
];

export const mockJobs: AIJob[] = [
  {
    id: "1",
    slug: "openai-research-scientist",
    title: "Research Scientist — Large Language Models",
    company: "OpenAI",
    location: "San Francisco, CA",
    type: "full-time",
    remote: false,
    salary: "$300K - $500K",
    description: "Join OpenAI's research team to push the boundaries of language model capabilities.",
    requirements: ["PhD in ML/CS", "Published papers at top venues", "Experience with large-scale training"],
    tags: ["Research", "LLM", "ML"],
    applyUrl: "https://openai.com/careers",
    postedAt: "2026-07-10T00:00:00Z",
  },
  {
    id: "2",
    slug: "anthropic-ml-engineer",
    title: "Senior ML Engineer — Safety & Alignment",
    company: "Anthropic",
    location: "San Francisco, CA",
    type: "full-time",
    remote: true,
    salary: "$280K - $450K",
    description: "Work on making AI systems safe and beneficial at Anthropic.",
    requirements: ["5+ years ML engineering", "Experience with RLHF", "Strong Python skills"],
    tags: ["ML Engineering", "Safety", "Alignment"],
    applyUrl: "https://anthropic.com/careers",
    postedAt: "2026-07-09T00:00:00Z",
  },
  {
    id: "3",
    slug: "google-ai-product-manager",
    title: "Product Manager — Gemini Platform",
    company: "Google DeepMind",
    location: "Mountain View, CA",
    type: "full-time",
    remote: false,
    salary: "$250K - $400K",
    description: "Lead product strategy for Google's Gemini AI platform.",
    requirements: ["5+ years PM experience", "AI/ML product background", "Technical degree"],
    tags: ["Product Management", "AI Platform", "Gemini"],
    applyUrl: "https://careers.google.com",
    postedAt: "2026-07-08T00:00:00Z",
  },
];

export const mockCompanies: Company[] = [
  {
    id: "1",
    slug: "openai",
    name: "OpenAI",
    description: "AI research company developing safe and beneficial artificial general intelligence.",
    logoUrl: "/logos/openai.svg",
    websiteUrl: "https://openai.com",
    founded: "2015",
    headquarters: "San Francisco, CA",
    employees: "3,000+",
    funding: "$13.3B",
    products: ["ChatGPT", "GPT-5", "DALL-E", "Sora", "Whisper"],
    tags: ["LLM", "AGI", "Research"],
  },
  {
    id: "2",
    slug: "anthropic",
    name: "Anthropic",
    description: "AI safety company building reliable, interpretable, and steerable AI systems.",
    logoUrl: "/logos/anthropic.svg",
    websiteUrl: "https://anthropic.com",
    founded: "2021",
    headquarters: "San Francisco, CA",
    employees: "1,500+",
    funding: "$7.6B",
    products: ["Claude", "Claude Code", "Constitutional AI"],
    tags: ["AI Safety", "LLM", "Research"],
  },
  {
    id: "3",
    slug: "google-deepmind",
    name: "Google DeepMind",
    description: "AI research lab aiming to solve intelligence and advance science.",
    logoUrl: "/logos/google.svg",
    websiteUrl: "https://deepmind.google",
    founded: "2010",
    headquarters: "London, UK",
    employees: "2,500+",
    funding: "Alphabet subsidiary",
    products: ["Gemini", "AlphaFold", "Veo", "Imagen"],
    tags: ["Research", "Multimodal", "Science"],
  },
];
